name: Deploy Service Discovery

on:
  push:
    branches: [ "main" ]
    paths:
      - 'SPS-ms-service-discovery/**'
      - '.github/workflows/deploy-service-discovery.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        run: |
          cd SPS-RedNorte-Infraestructura
          docker compose build ms-service-discovery
          docker compose push ms-service-discovery

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/rednorte-monorepo
            git pull origin main
            cd SPS-RedNorte-Infraestructura
            sudo docker compose pull ms-service-discovery
            sudo docker compose up -d --no-deps ms-service-discovery


